services:
  - type: web
    name: navya-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: SESSION_ID
        sync: false
      - key: BOT_NUMBER
        sync: false
      - key: SIGHTENGINE_USER
        sync: false
      - key: SIGHTENGINE_SECRET
        sync: false
      - key: OWNER_NUMBER
        sync: false
      - key: PORT
        value: 8080