services:
  - type: web
    name: navya-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_NAME
        value: Navya
      - key: BOT_NUMBER
        sync: false
      - key: OWNER_NUMBER
        sync: false
      - key: SIGHTENGINE_USER
        sync: false
      - key: SIGHTENGINE_SECRET
        sync: false
      - key: PORT
        value: 8080