services:
  - type: web
    name: navya
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_NAME
        sync: false
      - key: OWNER_NAME
        sync: false
      - key: BOT_NUMBER
        sync: false
      - key: OWNER_NUMBER
        sync: false
      - key: PREFIX
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: HF_KEY
        sync: false
      - key: SIGHTENGINE_USER
        sync: false
      - key: SIGHTENGINE_SECRET
        sync: false
      - key: PORT
        value: 10000