/**
 * Sing Downloader - Absolute Mobile Playback Fix
 * Bypasses standard utils/converter to force a true WhatsApp-native Ogg Opus stream
 */

const yts = require('yt-search');
const fs = require('fs');
const path = require('path');
const axios = require('axios');
const { exec } = require('child_process');
const APIs = require('../../utils/api');

module.exports = {
    name: 'sing',
    aliases: ['sv', 'voiceplay'],
    category: 'media',
    description: 'Download audio from YouTube as a guaranteed mobile-playable voice note',
    usage: '.sing <song name or YouTube link>',

    async execute(sock, msg, args) {
        const chatId = msg.key.remoteJid;
        // Create unique filenames for safe parallel execution
        const timestamp = Date.now();
        const tempDir = path.join(__dirname, '../../temp');
        const inputPath = path.join(tempDir, `input_${timestamp}`);
        const outputPath = path.join(tempDir, `output_${timestamp}.ogg`);

        try {
            const text = args.join(' ');
            if (!text) {
                return await sock.sendMessage(chatId, {
                    text: 'Usage: .sing <song name or YouTube link>'
                }, { quoted: msg });
            }

            let video;
            if (text.includes('youtube.com') || text.includes('youtu.be')) {
                video = { url: text };
            } else {
                const search = await yts(text);
                if (!search || !search.videos.length) {
                    return await sock.sendMessage(chatId, { text: 'No results found.' }, { quoted: msg });
                }
                video = search.videos[0];
            }

            // Ensure our working temporary workspace directory exists
            if (!fs.existsSync(tempDir)) {
                fs.mkdirSync(tempDir, { recursive: true });
            }

            // Trigger "Recording..." indicator instantly
            await sock.sendPresenceUpdate('recording', chatId);

            await sock.sendMessage(chatId, {
                image: { url: video.thumbnail },
                caption: `🎤 *Navya* is preparing to sing: *${video.title}*\n\n_Please give me a moment while i sing for you..._`
            }, { quoted: msg });

            let audioBuffer;
            let downloadSuccess = false;

            const apiMethods = [
                { name: 'EliteProTech', method: () => APIs.getEliteProTechDownloadByUrl(video.url) },
                { name: 'Yupra', method: () => APIs.getYupraDownloadByUrl(video.url) },
                { name: 'Okatsu', method: () => APIs.getOkatsuDownloadByUrl(video.url) },
                { name: 'Izumi', method: () => APIs.getIzumiDownloadByUrl(video.url) }
            ];

            for (const apiMethod of apiMethods) {
                try {
                    await sock.sendPresenceUpdate('recording', chatId);
                    const audioData = await apiMethod.method();
                    const audioUrl = audioData.download || audioData.dl || audioData.url;

                    if (!audioUrl) continue;

                    const audioResponse = await axios.get(audioUrl, {
                        responseType: 'arraybuffer',
                        timeout: 90000,
                        headers: {
                            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                            'Accept': '*/*'
                        }
                    });

                    audioBuffer = Buffer.from(audioResponse.data);
                    if (audioBuffer && audioBuffer.length > 0) {
                        downloadSuccess = true;
                        break;
                    }
                } catch (err) { continue; }
            }

            if (!downloadSuccess || !audioBuffer) throw new Error('Download failed');

            // Write raw downloaded stream chunk out to storage disk
            fs.writeFileSync(inputPath, audioBuffer);

            await sock.sendPresenceUpdate('recording', chatId);

            // ─── THE FFMPEG TRANSCODING FIX ───
            // We invoke FFmpeg to output an exact Ogg container (`-f ogg`) using the Opus voice codec (`-acodec libopus`)
            // paired with a 16kHz audio sample rate (`-ar 16000`) and mono channel output (`-ac 1`).
            // This mirrors the absolute identical format generated by recording an audio message inside the WhatsApp mobile app.
            await new Promise((resolve, reject) => {
                exec(`ffmpeg -i "${inputPath}" -vn -c:a libopus -b:a 32k -vbr on -ar 16000 -ac 1 -f ogg "${outputPath}" -y`, (error) => {
                    if (error) return reject(error);
                    resolve();
                });
            });

            const finalVoiceBuffer = fs.readFileSync(outputPath);

            await sock.sendPresenceUpdate('recording', chatId);

            // Send voice note with correct profile flags and native codec matching signatures
            await sock.sendMessage(chatId, {
                audio: finalVoiceBuffer,
                mimetype: 'audio/ogg; codecs=opus',
                ptt: true
            }, { quoted: msg });

        } catch (err) {
            console.error('Sing absolute error:', err);
            await sock.sendMessage(chatId, { text: '❌ Failed to complete performance audio.' }, { quoted: msg });
        } finally {
            // Clean up temporary audio artifacts cleanly on every process execution finish
            try { if (fs.existsSync(inputPath)) fs.unlinkSync(inputPath); } catch (_) { }
            try { if (fs.existsSync(outputPath)) fs.unlinkSync(outputPath); } catch (_) { }
        }
    }
};